### ISSUE TITLE
CCSE bug: functions in `Game.customReincarnate` and `Game.customAscend` are called even if `bypass != 1`

### ISSUE THREAD

**Issue by staticvariablejames** [klattmose/klattmose.github.io#11]
This happens because `Function.prototype.toString()` method preserves whitespaces, so the last few characters of `Game.Ascend`, for example, are `}	 	}` instead of `}}`. Hence the code injected by `CCSE.SliceCodeIntoFunction` is still outside of the `if(bypass)` block.

[Adding a custom `if(bypass == 1)` check seems to be the simplest solution here.](https://github.com/staticvariablejames/CCSE-fork/commit/46c9fd23e3875149977708a15a4e0ad761ae527a)

**Comment by klattmose** [comment]
Did I really not check that? Wow. Fixed now.
