### ISSUE TITLE
IdleTrading seems to freeze the game after a short time

### ISSUE THREAD

**Issue by azaquaz** [klattmose/klattmose.github.io#12]
Upon removing the mod, this stopped happening. The only other mod I have loaded is Spiced Cookies (https://github.com/staticvariablejames/SpicedCookies)

**Comment by klattmose** [comment]
Unfortunately I am unable to replicate this. Can you take a screenshot of the Stats page (which shows the version of the mod you're using) as well as a screenshot of the console after it freezes (F12 to bring up the dev tools)

**Comment by azaquaz** [comment]
Here's the console:
![image](https://user-images.githubusercontent.com/32604800/98027813-38a03980-1ddb-11eb-816d-4bf96d3a0035.png)

And here's the statistics page:
![image](https://user-images.githubusercontent.com/32604800/98027913-5a99bc00-1ddb-11eb-885e-f42e2305332c.png)
For some reason it doesn't have the version of Idle Trading.

**Comment by klattmose** [comment]
It looks like it's failing because the stock market minigame isn't loaded. Have you unlocked it by spending a sugar lump to upgrade banks? Either way, that's definitely a bug I need to fix.

**Comment by klattmose** [comment]
Fix is in place for the problem I mentioned. I think it should fix things for you. Try it out, the version should be 1.5.

**Comment by azaquaz** [comment]
Yes, I don't have the minigame unlocked yet because I had to move to a new computer and couldn't recover my save. It works now, thanks!
