### ISSUE TITLE
Having any hotkeys set to number keys with Klattmose Utilities makes it impossible to type values with those numbers into Idle Trading fields

### ISSUE THREAD

**Issue by azaquaz** [klattmose/klattmose.github.io#13]
Instead, the hotkey activates and the browser loses focus of the field. I'm using chrome, with Idle Trading version 1.5 and Klattmose Utilities version 2.12.

**Comment by azaquaz** [comment]
Also, may I ask for some labels on Idle Trading? I'm assuming the left field is the buy-at number and the right is the sell-at number but since they all initialized to -1 and there's no explanation I can find, I really have no idea.

**Comment by klattmose** [comment]
You can collapse the Klattmose Utilities menu (with the little - next to the name). Doing so prevents the hotkeys from activating, but only while in the Options menu.

**Comment by klattmose** [comment]
Idle Trading 1.6 now has Buy at and Sell at labels
