### ISSUE TITLE
CCSE bug/feature request: Don't inject variable `objKey` in minigame methods

### ISSUE THREAD

**Issue by staticvariablejames** [klattmose/klattmose.github.io#14]
Currently, functions like `CCSE.ReplaceGrimoire` inject the variable `objKey` into the minigames, so any mod that wishes to modify minigame methods must supply `objKey` in addition to the variable `M` that is already present on Cookie Clicker itself.

I implemented a fix [here](https://github.com/staticvariablejames/CCSE-fork/compare/cda657496e51eb7ecfba73ca380297cbd5f13d62...1a4154d8f2be1891cda1b02066aa1f98eb8cfc3b).

**Comment by klattmose** [comment]
I'll be honest, my initial reaction was "Use the freaking hooks, that's what they're there for!" But yeah, that's a bit of litter that shouldn't be there. I implemented it a little differently than you did, but that's just preferences.
