### ISSUE TITLE
Predict Sugar Lump type for Fortune Cookie

### ISSUE THREAD

**Issue by sanscriptum** [klattmose/klattmose.github.io#16]
If I understood the wiki correctly, RNG for SLs works similarly to what is used for spells and etc. Is it possible to add support for SL type prediction as well? Although it can be influenced with Dragon Curve and some achievements, so I'm not sure.

**Comment by klattmose** [comment]
While sugar lump type is seeded random like grimoire spells, it's seeded based on the millisecond the previous lump is harvested. By the time the prediction is generated and shown to the player, said prediction is obsolete.

**Comment by sanscriptum** [comment]
So it's possible to reroll desired SL type then? Might be an idea for a new userscript in that case.

**Comment by sanscriptum** [comment]
[I think I found the mod that fits my needs perfectly, leaving the link for posterity.](https://github.com/staticvariablejames/ChooseYourOwnLump)
