### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'magic' of undefined", source: file:///S:/steam/steamapps/common/Cookie%20Clicker/resources/app/src/index.html (3)

### ISSUE THREAD

**Issue by EntranceJew** [klattmose/klattmose.github.io#23]
KlattmoseUtilities's autospell hotkey example function creates an error in the steam version's console if enabled before the minigame is activated. It may seem like a "then don't do that" situation but it's easy to overlook when reloading and I'm used to piano-roll mashing all the numpad keys.

**Comment by klattmose** [comment]
Updated the default configuration to check if M exists before referencing a property of it. It will need to be redownloaded and restored to default config to get the change...

Or just change the code for Autospell to 

```js
var M = Game.Objects["Wizard tower"].minigame;
if(M && M.magic == M.magicM) M.castSpell(M.spells["haggler's charm"]);
```
