### ISSUE TITLE
Style Injector + More Helpers

### ISSUE THREAD

**Issue by EntranceJew** [klattmose/klattmose.github.io#28]
Rather than PR it, I'll just propose this change via gist:
https://gist.github.com/EntranceJew/74a6d541ba20f14a3b84ad85468e5054

Basically adds a style injector helper; maybe you might consider adding a means to pool the styles from several mods into a single tag. An example use case for this is with the addition of a new vanilla-styled checkbox element that is a suitable replacement for ToggleButtons with more visual clarity for their state / purpose.

Also a PasswordBox variant for InputBox since I've noticed at least two people trying to accomplish this via prompts.

**Comment by klattmose** [comment]
Cool. I put them in 2.028 beta
