### ISSUE TITLE
I can't figure out how to save data

### ISSUE THREAD

**Issue by Gulli03** [klattmose/klattmose.github.io#29]
I copied this code from the [CCSE documentation](https://klattmose.github.io/CookieClicker/CCSE-POCs/) page for saving data:

`CCSE.customSave.push(function(){
	CCSE.save.OtherMods.MyMod = MyMod.config;
});`

Then I substituted "MyMod" with my actual Modname.

After saving and reloading the game everytime the game tried to save it would throw the following error and freeze:

> Uncaught TypeError: Cannot set property 'MyModName' of undefined

**Comment by klattmose** [comment]
Use 
```js
CCSE.config.OtherMods.MyMod
```
instead. I've updated the documentation.
