### ISSUE TITLE
Some upgrades's description went missing if localized.

### ISSUE THREAD

**Issue by TsFreddie** [klattmose/klattmose.github.io#30]
"Tombola computing" and "Mice clicking mice" are known to have said issues. Haven't tried to check every upgrades.

![image](https://user-images.githubusercontent.com/3797859/133360547-a293f313-7583-4d88-9300-705496a4c9f9.png)
![image](https://user-images.githubusercontent.com/3797859/133360557-8ec66ca6-51a3-449f-b243-f59b6d5d872c.png)

Related: https://github.com/TeeworldsCN/CookieClickerCN/issues/6

**Comment by klattmose** [comment]
Fixed in v2.029
