### ISSUE TITLE
Localized quotes in upgrades get overriden back to english

### ISSUE THREAD

**Issue by TsFreddie** [klattmose/klattmose.github.io#31]
Without CCSE:
![image](https://user-images.githubusercontent.com/3797859/133374429-60cd0b69-fbf0-4eed-9c18-b5ef6b8324db.png)

With CCSE:
![image](https://user-images.githubusercontent.com/3797859/133374462-3c536ea1-4b9d-488d-9f69-2d59ca0d75f8.png)

Seems like all upgrades were affected.

**Comment by klattmose** [comment]
Fixed in v2.029
