### ISSUE TITLE
Steam version is breaking upgrade tooltips

### ISSUE THREAD

**Issue by LJNeon** [klattmose/klattmose.github.io#33]
I disabled all of my mods and the problem was fixed, enabling only CCSE (all of my other mods were still disabled) made the problem re-appear. Due to this I am entirely sure this is a CCSE problem, not a problem with any other mod or even how any other mod uses CCSE.
![image](https://user-images.githubusercontent.com/23249107/133912064-adaab0b8-6c34-44ca-82a6-66462e70e91f.png)

**Comment by klattmose** [comment]
Can you verify you are using the latest version? v2.029 went live today and made a change to fix a similar problem for localized upgrade tooltips.

**Comment by LJNeon** [comment]
Ah, good timing! That update does appear to have fixed it.
