### ISSUE TITLE
Horticookie: The game freeze

### ISSUE THREAD

**Issue by unlucky1251** [klattmose/klattmose.github.io#34]
The game OK until I installed the new 4.0 version, when the game launched the game seem normal but when I go to Options the game stop producing cookies.
Here's the mod list I enabled:
CCSE
Cookie Assistant
CookiStocker
Best Deal Helper
News Fixer
Horticookie
![20210919111731_1](https://user-images.githubusercontent.com/90997914/133915355-7dd7132c-f606-4fa1-bcff-8ff216c02c33.jpg)

**Comment by klattmose** [comment]
Disable all mods except CCSE and Horticookie and verify that the game works with just them. Then enable the other mods one at a time to find the conflict. Once you've found that, give me the link to it so I can debug.

**Comment by unlucky1251** [comment]
I disabled all the mods except CCSE and Horticookie, it stills freeze the game

**Comment by klattmose** [comment]
Activate the devconsole ([guide](https://steamcommunity.com/sharedfiles/filedetails/?id=2602063672)) and post the error message that happens.

**Comment by unlucky1251** [comment]
Is this one?
![Screenshot 2021-09-19 220909](https://user-images.githubusercontent.com/90997914/133932621-113114f0-894c-4818-8f7e-aada5908fe44.png)

**Comment by klattmose** [comment]
That's the one. 

But it doesn't make sense. From your previous screenshot it looks like you have the latest version of CCSE, which has CheckBox defined. Can you redownload it (https://klattmose.github.io/CookieClicker/SteamMods/CCSE.zip?v=2.029) and see if that fixes it?

**Comment by unlucky1251** [comment]
It fixed! Thanks
