### ISSUE TITLE
[Idle Trading] Change buy function to <= price

### ISSUE THREAD

**Issue by hyoretsu** [klattmose/klattmose.github.io#36]
Having just ascended for the first time after a really long time, we don't always have enough cookies to buy all available stocks at the "Buy at" price, so it pretty much doesn't work since only a few get bought and we gotta do the rest manually.

**Comment by klattmose** [comment]
Not sure what the request is. The "Buy at" price means "if the goods price is <= the Buy at price, buy as many as possible."

**Comment by hyoretsu** [comment]
Nvm, it works but per stock market tick.
