### ISSUE TITLE
Black hole inverter not saving

### ISSUE THREAD

**Issue by Austin001316** [klattmose/klattmose.github.io#37]
Every time i reload my save, all black hole achievements and buildings get reset

**Comment by klattmose** [comment]
What version of Black hole inverter and CCSE are you using (shown in the Stats menu). Also, browser or Steam?

**Comment by Austin001316** [comment]
Steam, CCSE 2.030, Black hole 1.11. I have figured out this issue is also affecting decide your destiny's (1.3) ascended upgrades. Only happens when I close the game but everything related to them is reset

**Comment by klattmose** [comment]
It seems like something is preventing the mod save data from loading properly. This could happen if there is an error caused by one mod, which would prevent further code execution (and loading data for subsequent mods). Try disabling all mods and re-enabling them one at a time until the save data starts failing again. 

Or enable DEV mode and see what error message pops up.

**Comment by Austin001316** [comment]
I tried disabling every mod but ccse and the black hole inverter, still occurs

**Comment by klattmose** [comment]
Enable DEV mode and see what error message pops up.

**Comment by Austin001316** [comment]
![image](https://user-images.githubusercontent.com/91763031/135890975-cbb040b1-1ef4-4e1b-a295-bb3dcb249828.png)

I dont see anything that looks like an error

**Comment by klattmose** [comment]
Please type `CCSE.save(3)` into the console and post the output.

**Comment by Austin001316** [comment]
How to restart game to open console, so thats why there are some 0's
![image](https://user-images.githubusercontent.com/91763031/135902101-93279069-40ee-4ff7-8e4b-e6f8dff34b5e.png)

**Comment by klattmose** [comment]
Thanks for providing the debug info. Found the bug and fixed it in the latest version of CCSE (2.031). You'll need to redownload it ([link](https://klattmose.github.io/CookieClicker/SteamMods/CCSE.zip?v=2.031)) as Workshop support doesn't exist yet.
