### ISSUE TITLE
Black Hole Inverter Text not Displaying

### ISSUE THREAD

**Issue by AvianGeneticist** [klattmose/klattmose.github.io#38]
When mousing over the Black hole inverter, the description (should be "Inverts the flow of gravity to get the infinitely delicious cookies from an infinitely dense singularity.", looking in the source code) reads as simply "undefined".

**Comment by klattmose** [comment]
Are you using the latest version (v1.11)?

**Comment by AvianGeneticist** [comment]
> Are you using the latest version (v1.11)?

Just installed it, seems like it's all fixed now.
Was wondering if it'd be possible for you to change the order of achievements/upgrades, too. It's a minor thing, but it bothers me the the black hle achievements/upgrades come before the javascript console and the idleverse ones.

**Comment by klattmose** [comment]
Fixed the orders in v1.12
