### ISSUE TITLE
customStatsMenu does not seem to work

### ISSUE THREAD

**Issue by gr3ger** [klattmose/klattmose.github.io#40]
Currently trying out some modding but noticed I couldn't get custom lines on the stats screen working.
Not even the Timer sample successfully manages to add its version number to the stats screen
https://klattmose.github.io/CookieClicker/CCSE-POCs/TimerWidget.js

And this is my script
https://gr3ger.github.io/elderFrenzy.js

But it doesn't seem like the function passed to `Game.customStatsMenu` gets called at all in either scripts.

**Comment by klattmose** [comment]
It works fine for me. Can you post the console output starting with 

```js
Game.LoadMod('https://gr3ger.github.io/elderFrenzy.js')
```

**Comment by gr3ger** [comment]
Maybe it's a firefox issue then? Haven't tried any other browsers.
```
Loaded the mod https://gr3ger.github.io/elderFrenzy.js, elderFrenzy. main.js:1579:12
Loaded the mod https://klattmose.github.io/CookieClicker/CCSE.js, CCSE. main.js:1579:12
Mod "CCSE" added. main.js:1468:12
unreachable code after return statement
CCSE.js:103:3
unreachable code after return statement
CCSE.js line 219 > eval:103:3
unreachable code after return statement
CCSE.js:23:4
unreachable code after return statement
CCSE.js:40:4
unreachable code after return statement
16 CCSE.js:8:4
unreachable code after return statement
CCSE.js:26:4
unreachable code after return statement
CCSE.js:43:4
unreachable code after return statement
CCSE.js line 272 > eval:26:4
unreachable code after return statement
CCSE.js line 272 > eval:43:4
unreachable code after return statement
16 CCSE.js line 219 > eval:8:4
Adding extra stats
```

**Comment by klattmose** [comment]
I am also using Firefox. It looks like things should be working. You say nothing happens when you open the Stats menu?

**Comment by gr3ger** [comment]
Ah, I think another mod was interfering. Was using frozencookies for the golden cookie timers.
I should probably have checked that first. 

Thanks for verifying that it worked, and sorry for opening an issue without checking properly, haha.

**Comment by gr3ger** [comment]
And just for future reference, it does seem to work as long as FrozenCookies is loaded *after* CCSE
