### ISSUE TITLE
[Feature Request, CCSE] More hooks

### ISSUE THREAD

**Issue by AliceDTRH** [klattmose/klattmose.github.io#41]
Is there any possibility for new hooks? For example, if I want to run some code every time a golden cookie is clicked?

**Comment by klattmose** [comment]
`Game.customShimmerTypes['golden'].popFunc` will run every time a golden cookie is clicked. If you have any other hooks you'd like, let me know.

**Comment by AliceDTRH** [comment]
Oooh, nice. Thanks! I can't think of any right now and I will look into this popFunc thingy, it seems super useful.

**Comment by AliceDTRH** [comment]
Sorry to bug you, but do I register to the Game.customShimmerTypes['golden'].popFunc hook?

**Comment by klattmose** [comment]
CCSE still imitates the previous mod api, so it's a little less friendly. You should use 

```js
Game.customShimmerTypes['golden'].popFunc.push(yourFunction);
```

**Comment by AliceDTRH** [comment]
Ah, thank you! :)
