### ISSUE TITLE
Creating Custom News Items

### ISSUE THREAD

**Issue by RHornberger20** [klattmose/klattmose.github.io#45]
I was looking into modding the game so that I could add my own fun news items (to the news ticker at the top), and was wondering if CCSE would be updated in the future to include a function for more easily updating or changing news items. The main javascript file for the game has a randomized way of selecting news items that also bases it on how many upgrades you have and how many cookies you've made.

If there were any ideas for making custom news easier to edit, please let me know!

**Comment by klattmose** [comment]
Cookie Clicker already has a mod hook for custom news items.
