### ISSUE TITLE
Incompatible with FrozenCookies (browser)

### ISSUE THREAD

**Issue by antimuffin** [klattmose/klattmose.github.io#47]
If I have both FortuneCookie and FrozenCookies [https://github.com/Icehawk78/FrozenCookies] loaded at the same time and cast any spell, FrozenCookies begins to season switch frantically, making it Easter followed by Not Easter as fast as it can until the price of season switching again is infinite, switching thousands of times in under a minute.

I've tried loading the two mods in different orders, changing settings, etc.  Neither alone exhibits this behavior, so it's somehow an interaction between the two mods. I opened an issue over at the FrozenCookies repo first, since that is the most likely one that needs to be changed, but I wanted to alert you here as well.

**Comment by erbkaiser** [comment]
I suspect it's something in CCSE that messes up timer states.
Just enabling CCSE on an empy save with FC already loaded, but nothing enabled, triggers countless 'Research has begun' pop-ups as well as unlock the Elder Nap achievement. This should be impossible of course.

Enabling it on an existing save with FC in late game causes other effects like non-stop purchase of seasons or the elder pledge.

**Comment by TylorBane** [comment]
im going to attempt to bump this since it seems it's not getting any attention, i just ran into this bug myself so i'd really enjoy if it's fixed

**Comment by Hringingy** [comment]
I'd also like to bump this issue in the hopes that this gets some attention

**Comment by olaims** [comment]
Is nobody taking care of this? :(

**Comment by TylorBane** [comment]
> Is nobody taking care of this? 😢

Unfortunately, while frozen cookies doesn't disable steam achievements, meaning that Orteil doesnt see it as cheating, that doesn't mean that the author of this mod is in any way required to make their stuff compatible with it, and is most likely ignoring it for that reason, i agree, it sucks, as i feel i should be able to play my single player game however i want, the author of ccse has no obligation to fix this and it most likely wont get any attention

**Comment by NotWhiteRice** [comment]
this is a mod handler, it should be compatible with other mods

**Comment by erbkaiser** [comment]
> this is a mod handler, it should be compatible with other mods

If only... no, CCSE replaces Cookie Clicker functions with its own versions.

**Comment by klattmose** [comment]
To anyone still paying attention to this thread, if you could test out the beta version of CCSE (https://klattmose.github.io/CookieClicker/Beta/CCSE.js) for compatibility with Frozen Cookies, I would appreciate it. The frantic buying of Easter is fixed, but I'm not familiar with all the ins and out of Frozen Cookies to be sure that there aren't other, more subtle problems.

**Comment by erbkaiser** [comment]
Seems to work again with my fork of FC.
Thanks, klattmose.

I'll edit the readme and will be sure to test the 2.05 beta version with it.

**Comment by klattmose** [comment]
Fixed in v2.034 of CCSE on browser. Steam version will be updated when the base game gets updated on Steam as well.
