### ISSUE TITLE
Sum of probabilities > 100%

### ISSUE THREAD

**Issue by Doogie2K** [klattmose/klattmose.github.io#5]
![oddmath](https://user-images.githubusercontent.com/48888037/66596604-8d8b6500-eb73-11e9-9f16-43ef3c6f297a.png)

I've observed a couple of times now (the attached screenshot is one; I missed the other) that there are situations where the probabilities of a plant spawning using wood chips can add up to >100%, thus leading to negative odds of nothing happening. I'm not sure how the game handles this vs. how Horticookie handles this, but that math seems obviously wrong. Is something being calculated out of order? Should everything just be divided by the sum so it's forced to be <= 100% at the end? I'd need to sit down and think about it with a pen and paper to have an idea, but I thought it worth bringing to your attention.

**Comment by klattmose** [comment]
Thanks for the heads up. I'll take a look at it this weekend.

**Comment by klattmose** [comment]
Problem with the calculations when Wood Chips were involved
