### ISSUE TITLE
Autobuy

### ISSUE THREAD

**Issue by Flambozo** [klattmose/klattmose.github.io#53]
I often used the Cookiemonster AutoBuy script, and it was recently removed. I assume it was broken in an update and am wondering if you have any plans on fixing it. I'm not sure if this is even an issue but I don't know how to start a discussion or anything like that, I literally created this account to ask this question!

**Comment by klattmose** [comment]
Since I can't remember why I removed it, sure.

**Comment by Flambozo** [comment]
Much appreciated! After typing this I found your KU config save on your page and it still had the autobuy script, so I loaded it up. It still works except it stops whenever cookie monster determines it should bulk buy, this is solved by manually doing the bulk buy, but a fix would be nice.
