### ISSUE TITLE
[Question] What is the "Other mods" folder?

### ISSUE THREAD

**Issue by ndvarn** [klattmose/klattmose.github.io#54]
I browsed the repository, looking to learn a few things from it, and I found the folder "CookieClicker/Other mods", containing JavaScript files with names of some mods that aren't from this repository, such as Cookie Monster.
What do those scripts do?

**Comment by klattmose** [comment]
Those are mods created by other people that I downloaded for some reason. I honestly don't remember. I claim no credit for them, and the only reason I'm not deleting the folder now is in case something is depending on it.
