### ISSUE TITLE
Is this just me?

### ISSUE THREAD

**Issue by DentalDom** [klattmose/klattmose.github.io#56]
Hi! I love Cookie Clicker, was really happy to see the new update! 

It seems that the "Destiny" upgrades from prestige disappear every time that I save and quit the game... My computer HAS been acting sussy recently though, so I wouldn't even be surprised if it's steam that is just not managing the save file correctly. Strangely enough, the other new heavenly upgrades remain purchased, it's only the "Destiny" ones that disappear...

**Comment by klattmose** [comment]
I don't experience this behavior on my computer. Try exporting your save and reimporting it, to isolate whether Steam is at fault.

**Comment by DentalDom** [comment]
Oh hey! Thanks for your response; was thinking about you before I saw the response because I tried removing the CCSE folder from the mods folder just in case that THIS was what was creating the problem: it was not. It was really strange though, when I was loading the game without the CCSE folder, I had 129/129 heavenly upgrades?! Not even 129/138 lolol! So strange? I uninstalled CCSE and re-installed, and did the same for the whole game, and it went back to the usual problem...

(I did do the export/import after everything but it didn't help either, this is just really weird, don't worry about it if I'm the only one reporting it, I'm not surprised, like I said my computer is kinda sussy these days lol.)

**Comment by klattmose** [comment]
That's very strange. I can't think of anything that might cause this. If you're not too concerned, that's good, because I have no solution for you. At least it's somewhat manageable by using DEV mode or the debug menu to re-enable them (or just not closing the game).

I'm not going to close the issue, in case it's not just you and others come here to report it, or if either of us has any ideas.

**Comment by DentalDom** [comment]
You know what, I have a possible "lead" but I don't know anything about coding, so I don't actually know if this is a lead. I lied when I said that importing the save file did nothing, cause I just instantly tested if it fixed the problem. It's true that it doesn't fix it; I still have to keep the game running if I don't want to lose my upgrades, but if I import the save file after I've lost my upgrades, they do come back. I hadn't noticed on the first time because I did it the other way around (export, import, leave game, open game, check if upgrades are there). So, loading the correct save file does fix it, but only temporarily. So... Is that a lead or not really lol?

**Comment by klattmose** [comment]
Can you compare the exported save against the save file that Steam writes? My save file is at `C:\Program Files (x86)\Steam\steamapps\common\Cookie Clicker\resources\app\save` with the name `save.cki`. They'll both be gibberish, but you should be able to check things like the date modified and the file size.

**Comment by DentalDom** [comment]
Yeah so: when I leave a game, the save.cki file does "confirm" that it was modified 1 second ago, the file size is 6 bytes less than if I then re-open the game, import the save "html giga line" or however it is called (lol) and then re-do a save without leaving the game (is that what you wanted me to do or did I misunderstand?)

Here are some images; the sav3.cki is the "damaged" save and save.cki is the good stuff!
![Screenshot (161)](https://github.com/klattmose/klattmose.github.io/assets/133146928/85bb0890-bf55-4b4c-9d4b-c82a19b9738d)
![Screenshot (163)](https://github.com/klattmose/klattmose.github.io/assets/133146928/6157fa7a-ba32-4ab4-9a1f-1983e10b2d77)

**Comment by klattmose** [comment]
Could you attach the files to this issue? I've found a way to make sense of them, so we can see what differences there are.

To be clear, I'd like one file that gets generated by the game when it saves (you can force a save with ctrl-s), call it `save.cki`, and a second file where you export the save for the menu and paste it into the text editor of your choice, call it `export.txt`. 
![image](https://github.com/klattmose/klattmose.github.io/assets/4196664/bb58bcd7-c72b-4de6-b8d4-e48e9ec41ecd)

**Comment by DentalDom** [comment]
[save.zip](https://github.com/klattmose/klattmose.github.io/files/11447629/save.zip)
[export.txt](https://github.com/klattmose/klattmose.github.io/files/11447631/export.txt)
Had to compress, apparently GitHub doesn't like Cookie clicker's save file type... If somehow compressing it ruins it, I can send you with wormhole or any other file transfer thingy?

**Comment by klattmose** [comment]
The file made it through the compression fine, so no worries there.

Both files say that the prestige upgrades are bought, and I am once again completely stumped. 

Can you activate DEV mode and see if any error messages appear in the console on startup? To activate DEV mode, open `"C:\Program Files (x86)\Steam\steamapps\common\Cookie Clicker\resources\app\start.js"` 
and change line 12 from 
`let DEV=0;` 
to 
`let DEV=1;`.
Then restart the game.

**Comment by DentalDom** [comment]
![Screenshot (164)](https://github.com/klattmose/klattmose.github.io/assets/133146928/0b687095-a17a-40e1-a46e-a6df55af953d)

I didn't really pay attention to any mods that I have, to be honest I haven't played this in a few years but if it's another mod causing the bug, I'm SO sorry!

**Comment by klattmose** [comment]
It looks like you're using an older version of CCSE. It's up to v2.034 now, for compatibility with Cookie Clicker v2.052.

I thought Steam automatically updated mods?

**Comment by DentalDom** [comment]
Absolutely no idea?! I literally uninstalled and re-installed LOL!!! Scammed by GabeN?! How can it be :(...

Hmmmm well, can you just send me maybe? Or like... Guide me on how to do this; no idea how the hell I could have an old version!!!

**Comment by klattmose** [comment]
Try following these steps:

1. In the Manage Mods menu, deactivate all mods.
2. Close the game.
3. Go to https://steamcommunity.com/sharedfiles/filedetails/?id=2685465009 and unsubscribe.
4. Open the game
5. Save
6. Close the game
7. Resubscribe to CCSE
8. Open the game again, and re-enable CCSE.
9. Reload the game and check CCSE's version number.

**Comment by DentalDom** [comment]
It's still 2.031 LOL, I'm so confused?! 2.034 illegal in Canada or something (lool)?

**Comment by klattmose** [comment]
What on Earth...

Screw it. Manual override time. 

Go to `https://github.com/klattmose/klattmose.github.io/blob/master/CookieClicker/SteamMods/CCSE/main.js`, copy the file there, and paste it into `C:\Program Files (x86)\Steam\steamapps\common\Cookie Clicker\resources\app\mods\workshop\CCSE\main.js`. If Steam won't update the mod, we'll do it ourselves. 

While we're digging around in the files, it may be worth checking that there is only one CCSE folder floating around. Check in both `C:\Program Files (x86)\Steam\steamapps\common\Cookie Clicker\resources\app\mods\workshop` and `C:\Program Files (x86)\Steam\steamapps\common\Cookie Clicker\resources\app\mods\local`. If there's a CCSE folder in both of those locations, delete the one in `local`.

**Comment by DentalDom** [comment]
HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA There was one in "local" and removing it fixed the whole thing hahahahahahhaha... Didn't even have to sneak in your stuff. Man, thank you so much for all those efforts and time, I'm so sorry that the seed of the problem ended up being kinda clowny LOL!

**Comment by klattmose** [comment]
No worries. It's always something that seems dumb once you know the answer, but the trick is figuring it out. Glad things are working now.
