### ISSUE TITLE
Grandmapocalyse - No automatic background for non-English users

### ISSUE THREAD

**Issue by SpringsTS** [klattmose/klattmose.github.io#64]
Hello,

I noticed from some time that when Background selector is off or set on Automatic, the background does not change according to the current Grandmapocalyse phase.
But this happens only when my game is set on French, not English.

**Cause**
This happen because in CCSE code source, at line 1347:
`if(choice.name != 'Automatic')`
After looking in developper tools, the name Automatic is translated in the array. In the French game, it is stored as "Automatique".

**Solution**
Replace the "Automatic" string by its localisation:
`if(choice.name != loc('Automatic'))`

Tested successfully on my config via a mod.

**Comment by klattmose** [comment]
Fixed , thanks.

**Comment by SpringsTS** [comment]
Thank you for your quick reply.
