### ISSUE TITLE
[Suggestion] Building code splicing

### ISSUE THREAD

**Issue by Kuiper-Belt-Object-Pluto** [klattmose/klattmose.github.io#68]
It seems it's impossible to replace/splice code into the functions for buildings? They're built off Game.Objects and are called by this.func(). No clue if it's possible for you to currently modify them in CCSE or if it's even possible to add the functionality to modify them.

I've tried variations of Game.Objects.this.buy, Game.Object.buy, this.buy, etc to see if any of them could be evaluated to inject code... nope.

**Comment by klattmose** [comment]
CCSE already injects hooks into most building functions. See the code starting at line 1654 for where CCSE does it ([link](https://github.com/klattmose/klattmose.github.io/blob/22964ed9a26fbf6b845760091ac261d079c6c2be/CookieClicker/CCSE.js#L1654)).

The building functions themselves are accessed/called/referenced by something along the lines of `Game.Objects["Alchemy lab"].buy()` (for example).
