### ISSUE TITLE
CCSE Feature Request: merge the vanilla save game and the CCSE save game

### ISSUE THREAD

**Issue by staticvariablejames** [klattmose/klattmose.github.io#9]
Currently, to completely save the state of a modded Cookie Clicker save game, we need to track both the save game produced by the game's own "Export save" and CCSE's "Export custom save". This is time-consuming, as saving and reloading requires managing two files/strings, and error-prone, as there is the possibility of mismatching saves.

A simple solution would be adding a `vanillaSave` attribute to the `CCSE.save` object. This allows only the vanilla save to be exported (via the game's own "Export Save" feature) while bundling everything together in the CCSE save. Then a single "Import modded save" would take care of reloading everything.

**Comment by klattmose** [comment]
I don't like the idea of affecting how the game interacts with its own save. Also, there's already enough confusion caused by the HTTP and HTTPS versions that I don't want to add to it. 

I think, overall, it's better and more intuitive to keep the vanilla save and the mod data separate.

**Comment by staticvariablejames** [comment]
Adding a `vanillaSave` to the `CCSE.save` object would not affect how the game interacts with its own save, just how the game's save interacts with the modded save. I implemented what I meant here: <https://github.com/staticvariablejames/CCSE-fork/compare/634f985a21843da82a7cc00ab662fae74153c218...f7fc2fc>

**Comment by hyoretsu** [comment]
I second this. Orteil already gave us a new modding API.
